export const legalRoutes = {
  terms_of_use: "/conditions-generales-utilisation",
  privacy_policy: "/politique-confidentialite",
  legal_notice: "/mentions-legales",
  sales_terms: "/conditions-generales-vente",
} as const;

export function validateLegalContent(content: unknown): content is Array<{ id: string; title: string; body: string }> {
  return Array.isArray(content) && content.length > 0 && content.every((section) =>
    section && typeof section.id === "string" && typeof section.title === "string" && typeof section.body === "string" && section.title.trim() && section.body.trim(),
  ) && new Set(content.map((section) => section.id)).size === content.length;
}

export function isLegalDocumentReady(content: unknown) {
  return validateLegalContent(content) && !content.some((section) => /\[[^\]]*(?:COMPL[ÉE]TER|VALIDER|RENSEIGNER|CONFIRMER)[^\]]*\]/i.test(`${section.title} ${section.body}`));
}

export const legalDrafts = [
  { type: "legal_notice", title: "Mentions légales", sections: [
    ["Éditeur", "Brand Studio est édité par [À COMPLÉTER : raison sociale, forme juridique, capital si applicable, siège, SIREN, registre d’immatriculation et TVA]. Directeur de publication : [À COMPLÉTER]. Contact : [À COMPLÉTER : e-mail et téléphone]."],
    ["Hébergement", "[À COMPLÉTER : raison sociale, adresse et téléphone de l’hébergeur du site ; localisation de l’hébergement et des données Supabase]."],
    ["Propriété intellectuelle et droit à l’image", "Les contenus pédagogiques, interfaces et éléments graphiques de Brand Studio sont protégés. Leur reproduction ou diffusion au-delà des droits accordés nécessite une autorisation. Les contenus apportés par les utilisateurs restent leur propriété. Avant d’importer une image, un logo, une police ou un texte, l’utilisateur doit disposer des droits nécessaires, y compris de l’autorisation des personnes représentées lorsque requise. Les exports peuvent être utilisés pour la communication de sa marque, dans le respect des droits des tiers."],
    ["Signalement", "Pour signaler une atteinte à des droits ou un contenu illicite : [À COMPLÉTER : contact]. Décrivez le contenu concerné, son emplacement et les droits invoqués."],
  ] },
  { type: "privacy_policy", title: "Politique de confidentialité", sections: [
    ["Responsable et contact", "[À COMPLÉTER : identité et coordonnées du responsable du traitement, contact pour les droits]. Vous pouvez également adresser une demande depuis /mes-donnees lorsque vous êtes connecté."],
    ["Données et finalités", "Les coordonnées du compte (nom, entreprise, e-mail), l’identifiant de connexion, l’état d’accès, les projets, réponses, fichiers et exports permettent de fournir le service : exécution du contrat. Les informations de paiement et justificatifs nécessaires à la comptabilité répondent aux obligations légales. La sécurité et la prévention des abus reposent sur l’intérêt légitime de protéger le service. Les champs obligatoires sont indiqués sur les formulaires ; sans eux, le service correspondant ne peut pas être fourni. Les numéros complets de carte sont traités par Stripe et ne sont pas stockés dans les tables applicatives de Brand Studio."],
    ["Destinataires et prestataires", "Les données sont accessibles aux personnes habilitées pour fournir le service et assister les utilisateurs. Supabase intervient pour l’authentification, les données et les fichiers, Stripe pour le paiement, Brevo pour les e-mails de service et OpenAI pour les fonctions d’assistance lorsqu’elles sont utilisées. [À COMPLÉTER : hébergeur, liste effective des prestataires activés, régions, accords de sous-traitance, transferts hors EEE et garanties applicables]. N’intégrez pas de données sensibles ou confidentielles de tiers dans les demandes d’assistance."],
    ["Conservation", "[À COMPLÉTER : durées effectives et procédure de purge des comptes, projets, exports, demandes de droits, journaux, preuves contractuelles et sauvegardes ; traitement des comptes inactifs]. Les données nécessaires à une obligation légale ou à la défense de droits sont conservées séparément pour cette seule finalité, pendant la durée applicable."],
    ["Cookies et sauvegarde locale", "Des cookies de session permettent la connexion. Le navigateur conserve aussi les préférences d’affichage et des réponses pour la sauvegarde locale/hors connexion. Ces mécanismes servent au fonctionnement du service. [À VALIDER : inventaire des cookies et durées, contenus externes et absence de traceurs publicitaires ou de mesure non exemptés]. Les traceurs facultatifs, s’ils sont ajoutés, nécessitent un choix préalable et révocable. La suppression d’un compte serveur ne supprime pas automatiquement les copies exportées ou stockées sur vos appareils."],
    ["Vos droits", "Vous pouvez demander accès, rectification, effacement, limitation, opposition et, lorsque les conditions sont réunies, portabilité de vos données. Un retrait de consentement n’affecte pas les traitements antérieurs. Une réponse est apportée en principe sous un mois, avec prolongation motivée dans les cas prévus. Un export des données du projet est disponible dans /mes-donnees. Vous pouvez adresser une réclamation à la CNIL, www.cnil.fr. Aucune pièce d’identité ne doit être envoyée spontanément ; une vérification proportionnée peut être demandée en cas de doute raisonnable."],
    ["Sécurité", "Les contrôles d’accès limitent l’accès aux données du compte ; les opérations sensibles sont vérifiées côté serveur. [À VALIDER : habilitations, sauvegardes et restauration, chiffrement, surveillance, gestion des incidents et tests réguliers]. Aucun dispositif ne garantit une sécurité absolue. En cas de violation, les obligations de notification et d’information sont évaluées selon les risques et les délais applicables."],
    ["Prospection", "Les e-mails nécessaires au compte et aux achats sont distincts de la prospection. Aucun consentement marketing n’est déduit de l’acceptation des CGU. [À VALIDER : absence de campagnes commerciales ou préciser leur base légale, preuve du consentement lorsque requis et lien de désinscription dans chaque message]."],
  ] },
  { type: "terms_of_use", title: "Conditions générales d’utilisation", sections: [
    ["Objet et accès", "Brand Studio propose des modules pédagogiques, exercices, projets de marque et exports. L’accès dépend de l’offre souscrite et d’un compte personnel. Éditeur et contact : [À COMPLÉTER]. Public et conditions d’éligibilité : [À COMPLÉTER]."],
    ["Compte et sécurité", "Fournissez des coordonnées exactes et protégez vos identifiants. Ne partagez pas votre compte et signalez sans délai un accès suspect. Les tentatives d’accès aux projets d’autrui, la diffusion de contenus illicites et la perturbation du service sont interdites."],
    ["Contenus et droits", "Vous restez titulaire des droits sur vos contenus. Vous autorisez uniquement les opérations nécessaires à leur stockage, affichage et export pour fournir le service. Vous devez disposer des licences, autorisations de reproduction et droits à l’image nécessaires. Les exports de votre projet sont utilisables dans votre activité ; cette faculté ne donne pas le droit de revendre les modules ou de redistribuer les contenus pédagogiques de Brand Studio."],
    ["Assistance et résultats", "Les suggestions automatiques sont des propositions à vérifier. Elles ne garantissent ni l’originalité juridique, ni la disponibilité d’une marque, ni un résultat commercial. Vérifiez les droits des tiers et l’exactitude des contenus avant de les publier."],
    ["Disponibilité et fin d’accès", "Les maintenances et incidents peuvent affecter l’accès. [À COMPLÉTER : engagements de disponibilité, assistance, suspension proportionnée avec information, résiliation et délai d’export avant fermeture]. Les droits légaux applicables aux consommateurs demeurent réservés."],
    ["Données et évolution", "La politique de confidentialité décrit les traitements et l’exercice des droits. Les versions des CGU sont datées ; une modification nécessitant une nouvelle acceptation est présentée avant la poursuite de l’utilisation selon son champ d’application. [À COMPLÉTER : droit applicable et modalités de règlement des différends sans priver un consommateur de ses protections impératives]."],
  ] },
  { type: "sales_terms", title: "Conditions générales de vente", sections: [
    ["Vendeur et clientèle", "[À COMPLÉTER : identité et coordonnées du vendeur ; offre B2B exclusivement ou B2B/B2C]. Ces conditions complètent les CGU pour les achats de Brand Studio."],
    ["Offre et prix", "Brand Studio est une expérience numérique guidée pour structurer sa marque et générer ses livrables, dont le Guide de Marque. Le prix total est de 289 euros, payé en une seule fois. L’accès est accordé pour 12 mois à compter de la confirmation du paiement, sans abonnement ni renouvellement automatique. Cette durée concerne uniquement les nouvelles commandes de cette offre ; elle ne modifie pas les accès historiques ou bêta. [À VALIDER : traitement de la TVA, prestations incluses, compatibilité, limites et assistance]."],
    ["Commande et paiement", "Le paiement est traité par Stripe. L’achat n’est validé qu’après confirmation du paiement. Un lien personnel permet de créer le compte. [À COMPLÉTER : remise de la confirmation contractuelle sur support durable, facturation, modalités en cas d’échec de paiement]."],
    ["Rétractation et résiliation", "[À COMPLÉTER selon le public et la qualification du service : droit de rétractation, point de départ, formulaire et fonctionnalité en ligne applicables, remboursement, demande expresse d’exécution anticipée et éventuelles exceptions légalement admises]. L’acceptation des CGV ne vaut pas renonciation automatique au droit de rétractation. [À COMPLÉTER : résiliation en ligne, préavis et effet sur l’accès pour les abonnements]."],
    ["Garanties, responsabilité et réclamations", "Les garanties légales applicables, notamment pour les contenus et services numériques vendus aux consommateurs, ne sont pas exclues. [À COMPLÉTER : modalités des garanties, assistance, coordonnées et site du médiateur de la consommation désigné, procédure de réclamation]."],
    ["Clients professionnels", "[À COMPLÉTER si applicable : conditions de règlement, pénalités de retard, indemnité forfaitaire de recouvrement et règlement des litiges]."],
  ] },
] as const;
