import Link from "next/link";
import { notFound } from "next/navigation";
import AdminAnswerValue from "@/app/ui/admin-answer-value";
import AdminGuideDownload from "@/app/ui/admin-guide-download";
import { getAdminUser, getAdminUserNeighbors } from "@/lib/admin-user-insights";

const date = (value: string) => value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "long", timeStyle: "short", timeZone: "Europe/Paris" }).format(new Date(value)) : "—";

export default async function AdminUserPage({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id);
  if (!Number.isInteger(id)) notFound();
  const [user, neighbors] = await Promise.all([getAdminUser(id), getAdminUserNeighbors(id)]);
  if (!user) notFound();
  const grouped = Map.groupBy(user.answers, (answer) => `${answer.modulePosition}:${answer.moduleTitle}`);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/admin" className="text-sm font-bold text-[#cf7430]">← Retour aux utilisateurs</Link><div className="flex gap-2">{neighbors.previous ? <Link className="rounded-full border border-[#eadfca] px-4 py-2 text-sm" href={`/admin/users/${neighbors.previous.id}`}>← Précédent</Link> : null}{neighbors.next ? <Link className="rounded-full border border-[#eadfca] px-4 py-2 text-sm" href={`/admin/users/${neighbors.next.id}`}>Suivant →</Link> : null}</div></div>
    <section className="bs-light-surface rounded-[1.6rem] border border-[#eadfca] bg-[linear-gradient(135deg,#fffdfa,#fff6e8)] p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-[#cf7430]">Fiche participante</p><h1 className="mt-4 font-[family:var(--font-cormorant)] text-5xl text-[#17213b]">{user.name}</h1><p className="mt-3 text-lg text-[#5d5752]">{user.company}</p><dl className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["E-mail",user.email],["Inscription",date(user.createdAt)],["Dernière activité",date(user.lastActivityAt)],["Progression",`${user.progress} %`]].map(([label,value]) => <div key={label}><dt className="text-xs font-black uppercase tracking-[0.14em] text-[#7a736d]">{label}</dt><dd className="mt-2 text-sm font-semibold text-[#17213b]">{value}</dd></div>)}</dl><div className="mt-6 flex flex-wrap gap-3"><a href={`/admin/users/${user.id}/export`} className="rounded-xl bg-[#17213b] px-5 py-3 text-xs font-black uppercase tracking-[0.12em] text-[#f5efe6]">Exporter les réponses</a>{user.guideExists ? <Link href={`/admin/users/${user.id}/guide`} className="rounded-xl border border-[#d7c8b7] bg-[#f8f1e6] px-5 py-3 text-xs font-black uppercase tracking-[0.12em] text-[#17213b]">Voir le guide de marque</Link> : null}</div></section>
    {user.projectId ? <div className="bs-light-surface rounded-2xl border border-[#eadfca] bg-[#fffaf2] p-5"><AdminGuideDownload userId={user.id} /><p className="mt-2 text-sm text-[#5d5752]">PDF généré à partir des réponses actuelles, même si le parcours est incomplet.</p></div> : <p className="rounded-2xl border border-[#eadfca] bg-[#fffaf2] p-5 text-sm text-[#5d5752]">Le Guide de Marque sera téléchargeable dès que cet utilisateur aura un projet.</p>}
    <section className="grid gap-4 md:grid-cols-2">{user.moduleProgress.map((moduleItem) => <article key={moduleItem.id} className="bs-light-surface rounded-[1.2rem] border border-[#eadfca] bg-white p-5"><div className="flex justify-between gap-3 text-sm font-bold text-[#17213b]"><span>{moduleItem.title}</span><span>{moduleItem.progress} %</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#eee6da]"><div className="h-full rounded-full bg-[linear-gradient(90deg,#df9b39,#f1cc56)]" style={{ width: `${moduleItem.progress}%` }} /></div></article>)}</section>
    {[...grouped.entries()].map(([key, answers]) => { const bySubmodule = Map.groupBy(answers, (answer) => answer.submoduleTitle); return <section key={key} className="space-y-4"><h2 className="border-b border-[#df9b39] pb-3 font-[family:var(--font-cormorant)] text-4xl text-[#17213b]">{answers[0].moduleTitle}</h2>{[...bySubmodule.entries()].map(([submodule, items]) => <article key={submodule} className="bs-light-surface rounded-[1.4rem] border border-[#eadfca] bg-white p-6"><h3 className="text-xs font-black uppercase tracking-[0.18em] text-[#cf7430]">{submodule}</h3><div className="mt-5 divide-y divide-[#eee3d4]">{items.map((answer) => <div key={answer.exerciseId} className="py-5 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-3"><h4 className="max-w-3xl font-semibold leading-6 text-[#17213b]">{answer.exerciseTitle}</h4><time className="text-xs text-[#7a736d]">{answer.updatedAt ? date(answer.updatedAt) : ""}</time></div><div className="mt-3"><AdminAnswerValue values={answer.values} type={answer.exerciseType} /></div></div>)}</div></article>)}</section>; })}
    {user.answers.length === 0 ? <p className="rounded-[1.2rem] border border-[#eadfca] bg-white p-8 text-center text-[#7a736d]">Aucune réponse enregistrée pour le moment.</p> : null}
  </div>;
}
