import Link from "next/link";
import { notFound } from "next/navigation";
import AdminAnswerValue from "@/app/ui/admin-answer-value";
import AdminGuideDownload from "@/app/ui/admin-guide-download";
import { getAdminUser, getAdminUserNeighbors } from "@/lib/admin-user-insights";

const date = (value: string) => value ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "long", timeStyle: "short", timeZone: "Europe/Paris" }).format(new Date(value)) : "—";

export default async function AdminUserPage({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id);
  if (!Number.isInteger(id)) notFound();
  const [user, neighbors] = await Promise.all([getAdminUser(id), getAdminUserNeighbors(id)]);
  if (!user) notFound();
  const grouped = Map.groupBy(user.answers, (answer) => `${answer.modulePosition}:${answer.moduleTitle}`);
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/admin" className="text-sm font-bold text-[var(--tyash-label-text)]">← Retour aux utilisateurs</Link><div className="flex gap-2">{neighbors.previous ? <Link className="rounded-full border border-[var(--border)] px-4 py-2 text-sm" href={`/admin/users/${neighbors.previous.id}`}>← Précédent</Link> : null}{neighbors.next ? <Link className="rounded-full border border-[var(--border)] px-4 py-2 text-sm" href={`/admin/users/${neighbors.next.id}`}>Suivant →</Link> : null}</div></div>
    <section className="bs-light-surface rounded-[1.6rem] border border-[var(--border)] bg-[image:var(--tyash-surface-gradient)] p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-[var(--tyash-label-text)]">Fiche participante</p><h1 className="mt-4 font-[family:var(--font-cormorant)] text-5xl text-[var(--heading-color)]">{user.name}</h1><p className="mt-3 text-lg text-[var(--text-primary)]">{user.company}</p><dl className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["E-mail",user.email],["Inscription",date(user.createdAt)],["Dernière activité",date(user.lastActivityAt)],["Progression",`${user.progress} %`]].map(([label,value]) => <div key={label}><dt className="text-xs font-black uppercase tracking-[0.14em] text-[var(--text-muted)]">{label}</dt><dd className="mt-2 text-sm font-semibold text-[var(--heading-color)]">{value}</dd></div>)}</dl><div className="mt-6 flex flex-wrap gap-3"><a href={`/admin/users/${user.id}/export`} className="rounded-xl bg-[#17213b] px-5 py-3 text-xs font-black uppercase tracking-[0.12em] text-[#f5efe6]">Exporter les réponses</a>{user.guideExists ? <Link href={`/admin/users/${user.id}/guide`} className="rounded-xl border border-[var(--border)] bg-[var(--surface-secondary)] px-5 py-3 text-xs font-black uppercase tracking-[0.12em] text-[var(--heading-color)]">Voir le guide de marque</Link> : null}</div></section>
    {user.projectId ? <div className="bs-light-surface rounded-2xl border border-[var(--border)] bg-[var(--tyash-subtle)] p-5"><AdminGuideDownload userId={user.id} /><p className="mt-2 text-sm text-[var(--text-primary)]">PDF généré à partir des réponses actuelles, même si le parcours est incomplet.</p></div> : <p className="rounded-2xl border border-[var(--border)] bg-[var(--tyash-subtle)] p-5 text-sm text-[var(--text-primary)]">Le Guide de Marque sera téléchargeable dès que cet utilisateur aura un projet.</p>}
    <section className="grid gap-4 md:grid-cols-2">{user.moduleProgress.map((moduleItem) => <article key={moduleItem.id} className="bs-light-surface rounded-[1.2rem] border border-[var(--border)] bg-[var(--card)] p-5"><div className="flex justify-between gap-3 text-sm font-bold text-[var(--heading-color)]"><span>{moduleItem.title}</span><span>{moduleItem.progress} %</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[var(--surface-secondary)]"><div className="h-full rounded-full bg-[image:var(--tyash-progress-gradient)]" style={{ width: `${moduleItem.progress}%` }} /></div></article>)}</section>
    {[...grouped.entries()].map(([key, answers]) => { const bySubmodule = Map.groupBy(answers, (answer) => answer.submoduleTitle); return <section key={key} className="space-y-4"><h2 className="border-b border-[var(--tyash-primary)] pb-3 font-[family:var(--font-cormorant)] text-4xl text-[var(--heading-color)]">{answers[0].moduleTitle}</h2>{[...bySubmodule.entries()].map(([submodule, items]) => <article key={submodule} className="bs-light-surface rounded-[1.4rem] border border-[var(--border)] bg-[var(--card)] p-6"><h3 className="text-xs font-black uppercase tracking-[0.18em] text-[var(--tyash-label-text)]">{submodule}</h3><div className="mt-5 divide-y divide-[#eee3d4]">{items.map((answer) => <div key={answer.exerciseId} className="py-5 first:pt-0 last:pb-0"><div className="flex flex-wrap items-start justify-between gap-3"><h4 className="max-w-3xl font-semibold leading-6 text-[var(--heading-color)]">{answer.exerciseTitle}</h4><time className="text-xs text-[var(--text-muted)]">{answer.updatedAt ? date(answer.updatedAt) : ""}</time></div><div className="mt-3"><AdminAnswerValue values={answer.values} type={answer.exerciseType} /></div></div>)}</div></article>)}</section>; })}
    {user.answers.length === 0 ? <p className="rounded-[1.2rem] border border-[var(--border)] bg-[var(--card)] p-8 text-center text-[var(--text-muted)]">Aucune réponse enregistrée pour le moment.</p> : null}
  </div>;
}
