-- À adapter avec l'URL de production et le secret stocké dans Supabase Vault.
-- Ne pas exécuter avant d'avoir configuré CRON_SECRET côté Vercel.
--
-- select cron.schedule(
--   'brand-studio-publish-scheduled',
--   '* * * * *',
--   $$ select net.http_get(
--     url := 'https://brand-studio-new.vercel.app/api/cron/publish-scheduled',
--     headers := jsonb_build_object(
--       'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'brand_studio_cron_secret')
--     )
--   ); $$
-- );
