begin;

-- This migration is deliberately additive. The legacy tables remain untouched
-- and continue to be the production source until an explicit application cutover.
create table if not exists public.content_releases (
  id uuid primary key default gen_random_uuid(),
  version_number bigint generated by default as identity,
  name text not null,
  status text not null check (status in ('draft', 'ready', 'published', 'archived')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  published_by uuid references auth.users(id) on delete set null,
  source_release_id uuid references public.content_releases(id) on delete set null,
  notes text,
  constraint content_releases_version_number_key unique (version_number)
);

create unique index if not exists content_releases_one_published_idx
  on public.content_releases ((status)) where status = 'published';

create table if not exists public.content_release_snapshots (
  release_id uuid primary key references public.content_releases(id) on delete cascade,
  schema_version integer not null default 1 check (schema_version > 0),
  modules jsonb not null default '[]'::jsonb check (jsonb_typeof(modules) = 'array'),
  brand_guide_settings jsonb not null default '{}'::jsonb check (jsonb_typeof(brand_guide_settings) = 'object'),
  pdf_settings jsonb not null default '{}'::jsonb check (jsonb_typeof(pdf_settings) = 'object'),
  interface_settings jsonb not null default '{}'::jsonb check (jsonb_typeof(interface_settings) = 'object'),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.application_release_state (
  id smallint primary key default 1 check (id = 1),
  published_release_id uuid not null references public.content_releases(id) on delete restrict,
  current_draft_release_id uuid references public.content_releases(id) on delete restrict,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.feature_configurations (
  id uuid primary key default gen_random_uuid(),
  release_id uuid not null references public.content_releases(id) on delete cascade,
  stable_key text not null,
  enabled boolean not null default false,
  admin_only boolean not null default false,
  rollout_percentage integer not null default 0 check (rollout_percentage between 0 and 100),
  allowed_user_ids bigint[] not null default '{}'::bigint[],
  configuration jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (release_id, stable_key)
);

create table if not exists public.admin_preview_answer_sets (
  id uuid primary key default gen_random_uuid(),
  admin_account_id bigint not null references public.client_access_codes(id) on delete cascade,
  release_id uuid not null references public.content_releases(id) on delete cascade,
  mode text not null check (mode in ('new_user', 'current_answers')),
  answers jsonb not null default '{}'::jsonb check (jsonb_typeof(answers) = 'object'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (admin_account_id, release_id, mode)
);

alter table public.user_answers
  add column if not exists content_release_id_at_answer_time uuid
    references public.content_releases(id) on delete set null;
alter table public.user_answers
  add column if not exists answer_schema_version integer not null default 1;
alter table public.admin_audit_logs
  add column if not exists release_id uuid references public.content_releases(id) on delete set null;

create or replace function public.is_admin(target_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.client_access_codes account
    where account.auth_user_id = target_user_id
      and account.is_active = true
      and (account.role = 'admin' or account.is_admin = true)
  );
$$;

revoke all on function public.is_admin(uuid) from public;
grant execute on function public.is_admin(uuid) to authenticated, service_role;

create or replace function public.guard_published_release_content()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  guarded_release_id uuid;
begin
  guarded_release_id := coalesce(new.release_id, old.release_id);
  if exists (
    select 1 from public.content_releases
    where id = guarded_release_id and status in ('published', 'archived')
  ) then
    raise exception 'published and archived release content is immutable';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists content_release_snapshots_immutable on public.content_release_snapshots;
create trigger content_release_snapshots_immutable
before update or delete on public.content_release_snapshots
for each row execute function public.guard_published_release_content();

drop trigger if exists feature_configurations_immutable on public.feature_configurations;
create trigger feature_configurations_immutable
before update or delete on public.feature_configurations
for each row execute function public.guard_published_release_content();

create or replace function public.clone_content_release(
  source_release_id uuid,
  draft_name text,
  replace_current_draft boolean default false
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  state_row public.application_release_state%rowtype;
  source_row public.content_releases%rowtype;
  next_release_id uuid;
begin
  if not public.is_admin(actor) then raise exception 'admin role required'; end if;
  if nullif(btrim(draft_name), '') is null then raise exception 'draft name required'; end if;

  select * into state_row from public.application_release_state where id = 1 for update;
  select * into source_row from public.content_releases where id = $1;
  if source_row.id is null then raise exception 'source release not found'; end if;

  if state_row.current_draft_release_id is not null then
    if not replace_current_draft then raise exception 'a current draft already exists'; end if;
    update public.content_releases
      set status = 'archived', updated_at = now()
      where id = state_row.current_draft_release_id and status in ('draft', 'ready');
  end if;

  insert into public.content_releases(name, status, created_by, source_release_id)
  values (btrim(draft_name), 'draft', actor, source_row.id)
  returning id into next_release_id;

  insert into public.content_release_snapshots(
    release_id, schema_version, modules, brand_guide_settings, pdf_settings,
    interface_settings, updated_by
  )
  select next_release_id, schema_version, modules, brand_guide_settings,
    pdf_settings, interface_settings, actor
  from public.content_release_snapshots
  where release_id = source_row.id;

  insert into public.feature_configurations(
    release_id, stable_key, enabled, admin_only, rollout_percentage,
    allowed_user_ids, configuration
  )
  select next_release_id, stable_key, enabled, admin_only, rollout_percentage,
    allowed_user_ids, configuration
  from public.feature_configurations
  where release_id = source_row.id;

  update public.application_release_state
  set current_draft_release_id = next_release_id, updated_at = now(), updated_by = actor
  where id = 1;

  insert into public.admin_audit_logs(
    admin_user_id, action_type, entity_type, entity_id, release_id, metadata
  ) values (
    actor, case when source_row.status = 'archived' then 'release_restored' else 'draft_created' end,
    'content_release', next_release_id::text, next_release_id,
    jsonb_build_object('source_release_id', source_row.id, 'replaced_existing_draft', replace_current_draft)
  );
  return next_release_id;
end;
$$;

create or replace function public.update_current_draft_snapshot(
  target_release_id uuid,
  snapshot_schema_version integer,
  snapshot_modules jsonb,
  snapshot_brand_guide_settings jsonb default '{}'::jsonb,
  snapshot_pdf_settings jsonb default '{}'::jsonb,
  snapshot_interface_settings jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
begin
  if not public.is_admin(actor) then raise exception 'admin role required'; end if;
  if snapshot_schema_version < 1 then raise exception 'invalid schema version'; end if;
  if jsonb_typeof(snapshot_modules) <> 'array' then raise exception 'modules must be an array'; end if;
  if not exists (
    select 1
    from public.application_release_state state
    join public.content_releases release on release.id = state.current_draft_release_id
    where state.id = 1
      and release.id = target_release_id
      and release.status = 'draft'
  ) then
    raise exception 'only the current draft can be updated';
  end if;

  update public.content_release_snapshots
  set schema_version = snapshot_schema_version,
      modules = snapshot_modules,
      brand_guide_settings = coalesce(snapshot_brand_guide_settings, '{}'::jsonb),
      pdf_settings = coalesce(snapshot_pdf_settings, '{}'::jsonb),
      interface_settings = coalesce(snapshot_interface_settings, '{}'::jsonb),
      updated_at = now(),
      updated_by = actor
  where release_id = target_release_id;

  update public.content_releases set updated_at = now() where id = target_release_id;
  insert into public.admin_audit_logs(
    admin_user_id, action_type, entity_type, entity_id, release_id
  ) values (actor, 'draft_updated', 'content_release', target_release_id::text, target_release_id);
end;
$$;

create or replace function public.mark_content_release_ready(
  target_release_id uuid,
  release_notes text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare actor uuid := auth.uid();
begin
  if not public.is_admin(actor) then raise exception 'admin role required'; end if;
  if nullif(btrim(release_notes), '') is null then raise exception 'release notes required'; end if;
  update public.content_releases release
  set status = 'ready', notes = btrim(release_notes), updated_at = now()
  from public.application_release_state state
  where state.id = 1
    and state.current_draft_release_id = release.id
    and release.id = target_release_id
    and release.status = 'draft';
  if not found then raise exception 'current draft not found'; end if;
  insert into public.admin_audit_logs(
    admin_user_id, action_type, entity_type, entity_id, release_id
  ) values (actor, 'release_marked_ready', 'content_release', target_release_id::text, target_release_id);
end;
$$;

create or replace function public.upsert_admin_preview_answers(
  target_release_id uuid,
  module_key text,
  module_answers jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  account_id bigint;
begin
  if not public.is_admin(actor) then raise exception 'admin role required'; end if;
  if nullif(btrim(module_key), '') is null then raise exception 'module key required'; end if;
  if jsonb_typeof(module_answers) <> 'object' then raise exception 'module answers must be an object'; end if;
  if not exists (
    select 1 from public.application_release_state
    where id = 1 and current_draft_release_id = target_release_id
  ) then raise exception 'preview answers require the current draft'; end if;

  select id into account_id
  from public.client_access_codes
  where auth_user_id = actor and is_active = true and (role = 'admin' or is_admin = true);

  insert into public.admin_preview_answer_sets(
    admin_account_id, release_id, mode, answers
  ) values (
    account_id, target_release_id, 'new_user',
    jsonb_build_object(module_key, module_answers)
  )
  on conflict (admin_account_id, release_id, mode)
  do update set
    answers = public.admin_preview_answer_sets.answers
      || jsonb_build_object(module_key, module_answers),
    updated_at = now();
end;
$$;

create or replace function public.clear_admin_preview_answers(target_release_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
begin
  if not public.is_admin(actor) then raise exception 'admin role required'; end if;
  delete from public.admin_preview_answer_sets preview
  using public.client_access_codes account
  where preview.release_id = target_release_id
    and preview.mode = 'new_user'
    and preview.admin_account_id = account.id
    and account.auth_user_id = actor;
end;
$$;

create or replace function public.update_draft_feature_configuration(
  target_release_id uuid,
  feature_key text,
  feature_enabled boolean,
  feature_admin_only boolean,
  feature_rollout_percentage integer,
  feature_allowed_user_ids bigint[] default '{}'::bigint[],
  feature_configuration jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare actor uuid := auth.uid();
begin
  if not public.is_admin(actor) then raise exception 'admin role required'; end if;
  if nullif(btrim(feature_key), '') is null then raise exception 'feature key required'; end if;
  if feature_rollout_percentage not between 0 and 100 then raise exception 'invalid rollout percentage'; end if;
  if not exists (
    select 1
    from public.application_release_state state
    join public.content_releases release on release.id = state.current_draft_release_id
    where state.id = 1 and release.id = target_release_id and release.status = 'draft'
  ) then raise exception 'only the current draft can be updated'; end if;

  insert into public.feature_configurations(
    release_id, stable_key, enabled, admin_only, rollout_percentage,
    allowed_user_ids, configuration
  ) values (
    target_release_id, btrim(feature_key), feature_enabled, feature_admin_only,
    feature_rollout_percentage, coalesce(feature_allowed_user_ids, '{}'::bigint[]),
    coalesce(feature_configuration, '{}'::jsonb)
  )
  on conflict (release_id, stable_key)
  do update set enabled = excluded.enabled,
    admin_only = excluded.admin_only,
    rollout_percentage = excluded.rollout_percentage,
    allowed_user_ids = excluded.allowed_user_ids,
    configuration = excluded.configuration,
    updated_at = now();

  insert into public.admin_audit_logs(
    admin_user_id, action_type, entity_type, entity_id, release_id, metadata
  ) values (
    actor, 'feature_configuration_updated', 'feature_configuration',
    btrim(feature_key), target_release_id,
    jsonb_build_object(
      'enabled', feature_enabled,
      'admin_only', feature_admin_only,
      'rollout_percentage', feature_rollout_percentage
    )
  );
end;
$$;

create or replace function public.publish_content_release(
  draft_release_id uuid,
  release_notes text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  state_row public.application_release_state%rowtype;
  target public.content_releases%rowtype;
begin
  if not public.is_admin(actor) then raise exception 'admin role required'; end if;
  if nullif(btrim(release_notes), '') is null then raise exception 'release notes required'; end if;

  select * into state_row from public.application_release_state where id = 1 for update;
  select * into target from public.content_releases where id = draft_release_id for update;
  if target.id is null or target.status <> 'ready' then
    raise exception 'release must be ready before publication';
  end if;
  if state_row.current_draft_release_id <> target.id then
    raise exception 'only the current draft can be published';
  end if;
  if state_row.published_release_id is null then
    raise exception 'published release reference is missing';
  end if;

  update public.content_releases
  set status = 'archived', updated_at = now()
  where id = state_row.published_release_id and status = 'published';
  if not found then raise exception 'current published release not found'; end if;

  update public.content_releases
  set status = 'published',
      notes = btrim(release_notes),
      published_at = now(),
      published_by = actor,
      updated_at = now()
  where id = target.id and status = 'ready';
  if not found then raise exception 'publication conflict'; end if;

  update public.application_release_state
  set published_release_id = target.id,
      current_draft_release_id = null,
      updated_at = now(),
      updated_by = actor
  where id = 1;

  insert into public.admin_audit_logs(
    admin_user_id, action_type, entity_type, entity_id, release_id, metadata
  ) values (
    actor, 'release_published', 'content_release', target.id::text, target.id,
    jsonb_build_object('previous_release_id', state_row.published_release_id, 'notes', btrim(release_notes))
  );
end;
$$;

revoke all on function public.clone_content_release(uuid, text, boolean) from public, anon;
revoke all on function public.update_current_draft_snapshot(uuid, integer, jsonb, jsonb, jsonb, jsonb) from public, anon;
revoke all on function public.mark_content_release_ready(uuid, text) from public, anon;
revoke all on function public.publish_content_release(uuid, text) from public, anon;
revoke all on function public.upsert_admin_preview_answers(uuid, text, jsonb) from public, anon;
revoke all on function public.clear_admin_preview_answers(uuid) from public, anon;
revoke all on function public.update_draft_feature_configuration(uuid, text, boolean, boolean, integer, bigint[], jsonb) from public, anon;
grant execute on function public.clone_content_release(uuid, text, boolean) to authenticated;
grant execute on function public.update_current_draft_snapshot(uuid, integer, jsonb, jsonb, jsonb, jsonb) to authenticated;
grant execute on function public.mark_content_release_ready(uuid, text) to authenticated;
grant execute on function public.publish_content_release(uuid, text) to authenticated;
grant execute on function public.upsert_admin_preview_answers(uuid, text, jsonb) to authenticated;
grant execute on function public.clear_admin_preview_answers(uuid) to authenticated;
grant execute on function public.update_draft_feature_configuration(uuid, text, boolean, boolean, integer, bigint[], jsonb) to authenticated;

alter table public.content_releases enable row level security;
alter table public.content_release_snapshots enable row level security;
alter table public.application_release_state enable row level security;
alter table public.feature_configurations enable row level security;
alter table public.admin_preview_answer_sets enable row level security;

drop policy if exists content_releases_read on public.content_releases;
create policy content_releases_read on public.content_releases for select
using (status = 'published' or public.is_admin());
drop policy if exists content_release_snapshots_read on public.content_release_snapshots;
create policy content_release_snapshots_read on public.content_release_snapshots for select
using (
  public.is_admin()
  or exists (
    select 1 from public.application_release_state
    where id = 1 and published_release_id = release_id
  )
);
drop policy if exists application_release_state_read on public.application_release_state;
create policy application_release_state_read on public.application_release_state for select
using (public.is_admin());
drop policy if exists feature_configurations_read on public.feature_configurations;
create policy feature_configurations_read on public.feature_configurations for select
using (
  public.is_admin()
  or exists (
    select 1 from public.application_release_state
    where id = 1 and published_release_id = release_id
  )
);
drop policy if exists preview_answer_sets_admin on public.admin_preview_answer_sets;
create policy preview_answer_sets_admin on public.admin_preview_answer_sets for all
using (
  public.is_admin()
  and exists (
    select 1 from public.client_access_codes account
    where account.id = admin_account_id and account.auth_user_id = auth.uid()
  )
)
with check (
  public.is_admin()
  and exists (
    select 1 from public.client_access_codes account
    where account.id = admin_account_id and account.auth_user_id = auth.uid()
  )
);

create or replace function public.get_published_content_release_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select published_release_id
  from public.application_release_state
  where id = 1;
$$;
revoke all on function public.get_published_content_release_id() from public, anon;
grant execute on function public.get_published_content_release_id() to authenticated;

-- Bootstrap V1 from the exact legacy content visible at migration time. This
-- copies data into new tables; it does not alter the legacy production source.
do $$
declare
  initial_release_id uuid;
  initial_modules jsonb;
begin
  if not exists (select 1 from public.application_release_state where id = 1) then
    select coalesce(
      jsonb_agg(module_snapshot order by module_position),
      '[]'::jsonb
    ) into initial_modules
    from (
      select
        module.position as module_position,
        jsonb_build_object(
          'stableKey', 'module_' || module.id,
          'legacyId', module.id,
          'title', module.title,
          'position', module.position,
          'isPublished', module.is_published,
          'videoUrl', coalesce(module.video_url, ''),
          'audioUrl', coalesce(module.audio_url, ''),
          'audioTranscript', coalesce(module.audio_transcript, ''),
          'contentHtml', coalesce(module.content_html, ''),
          'submodules', coalesce((
            select jsonb_agg(
              jsonb_build_object(
                'stableKey', 'submodule_' || submodule.id,
                'legacyId', submodule.id,
                'title', submodule.title,
                'position', submodule.position,
                'videoUrl', coalesce(submodule.video_url, ''),
                'audioUrl', coalesce(submodule.audio_url, ''),
                'audioTranscript', coalesce(submodule.audio_transcript, ''),
                'contentHtml', coalesce(submodule.content_html, ''),
                'exercises', coalesce((
                  select jsonb_agg(
                    jsonb_build_object(
                      'stableKey', 'exercise_' || exercise.id,
                      'legacyId', exercise.id,
                      'position', exercise.position,
                      'type', exercise.type,
                      'question', exercise.question,
                      'options', coalesce(exercise.options, '[]'::jsonb),
                      'explanation', coalesce(exercise.explanation, ''),
                      'answerPlaceholder', coalesce(exercise.answer_placeholder, ''),
                      'audioUrl', coalesce(exercise.audio_url, ''),
                      'audioTranscript', coalesce(exercise.audio_transcript, '')
                    ) order by exercise.position
                  )
                  from public.module_exercises exercise
                  where exercise.module_id = module.id
                    and exercise.submodule_id = submodule.id
                ), '[]'::jsonb)
              ) order by submodule.position
            )
            from public.brand_submodules submodule
            where submodule.module_id = module.id
          ), '[]'::jsonb)
        ) as module_snapshot
      from public.brand_modules module
      where module.is_published = true
    ) snapshot_rows;

    insert into public.content_releases(name, status, notes, published_at)
    values ('Version publiée initiale', 'published', 'Import non destructif du contenu historique', now())
    returning id into initial_release_id;

    insert into public.content_release_snapshots(release_id, schema_version, modules)
    values (initial_release_id, 1, initial_modules);
    insert into public.application_release_state(id, published_release_id)
    values (1, initial_release_id);
  end if;
end;
$$;

commit;
